name: Update Flake Dependencies

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update Dependencies (Flake Lock)

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix package manager
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure Cachix binary cache
        uses: cachix/cachix-action@v17
        with:
          name: ${{ secrets.CACHIX_CACHE_NAME }}
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Update flake.lock file
        id: update
        uses: DeterminateSystems/update-flake-lock@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-msg: "chore: update flake.lock"
          pr-labels: |
            dependencies
            automated

      - name: Build and push dependencies to Cachix cache
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        run: |
          nix-store --query --requisites $(nix-store --query --deriver $(nix build --print-out-paths .)) \
          | cachix push ${{ secrets.CACHIX_CACHE_NAME }}

      - name: Auto-merge dependency update PR
        if: ${{ steps.update.outputs.pull-request-number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ steps.update.outputs.pull-request-number }} --squash --delete-branch
